//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniBank.Resources.MenuMessages", typeof(MenuMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} has {2} balance .
        /// </summary>
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the account is not found, please try again.
        /// </summary>
        public static string AccountNotFoundMessage {
            get {
                return ResourceManager.GetString("AccountNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the account type not exist, please try again.
        /// </summary>
        public static string AccountTypeNotExist {
            get {
                return ResourceManager.GetString("AccountTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Account Type:
        ///1-Simple account
        ///2-Vip Account.
        /// </summary>
        public static string AccountTypeOptions {
            get {
                return ResourceManager.GetString("AccountTypeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected action is not exsist, please input action from the options above.
        /// </summary>
        public static string ActionNotExistMessage {
            get {
                return ResourceManager.GetString("ActionNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any time you want to cancel – input &apos;c&apos;.
        /// </summary>
        public static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string CancelValue {
            get {
                return ResourceManager.GetString("CancelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please try again.
        /// </summary>
        public static string ErrorInputMessage {
            get {
                return ResourceManager.GetString("ErrorInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter positive sum.
        /// </summary>
        public static string InvalidSumMessage {
            get {
                return ResourceManager.GetString("InvalidSumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-List all user  
        ///2-List all accounts for a given user with their current balance  
        ///3-Deposit from a given account
        ///4-Withdraw from a given account
        ///5-Create a new user  
        ///6-Create a new account for a user
        ///7-Delete users and accounts
        ///8-Exit.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are not accounts for this user yet.
        /// </summary>
        public static string NoAccountsExistMessage {
            get {
                return ResourceManager.GetString("NoAccountsExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are not users in the bank yet.
        /// </summary>
        public static string NoUsersExistMessage {
            get {
                return ResourceManager.GetString("NoUsersExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the id of the account please.
        /// </summary>
        public static string ReadAccountIdMessage {
            get {
                return ResourceManager.GetString("ReadAccountIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sum please.
        /// </summary>
        public static string ReadSumMessage {
            get {
                return ResourceManager.GetString("ReadSumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the id of the user please.
        /// </summary>
        public static string ReadUserIdMessage {
            get {
                return ResourceManager.GetString("ReadUserIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the user please.
        /// </summary>
        public static string ReadUserNameMessage {
            get {
                return ResourceManager.GetString("ReadUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the action was executed successfully.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of user {0} is {1}.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user is not found, please try again.
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
    }
}
